export const ALL_JOBS_REQUEST = "ALL_JOBS_REQUEST"
export const ALL_JOBS_SUCCESS = "ALL_JOBS_SUCCESS"
export const ALL_JOBS_FAIL = "ALL_JOBS_FAIL"

export const CREATE_JOB_REQUEST = "CREATE_JOB_REQUEST"
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS"
export const CREATE_JOB_FAIL = "CREATE_JOB_FAIL"

export const JOB_APPLY_REQUEST = "JOB_APPLY_REQUEST"
export const JOB_APPLY_SUCCESS = "JOB_APPLY_SUCCESS"
export const JOB_APPLY_FAIL = "JOB_APPLY_FAIL"

export const ASSIGNED_USER_REQUEST = "ASSIGNED_USER_REQUEST"
export const ASSIGNED_USER_SUCCESS = "ASSIGNED_USER_SUCCESS"
export const ASSIGNED_USER_FAIL = "ASSIGNED_USER_FAIL"

export const JOB_COMPLETED_REQUEST = "JOB_COMPLETED_REQUEST"
export const JOB_COMPLETED_SUCCESS = "JOB_COMPLETED_SUCCESS"
export const JOB_COMPLETED_FAIL = "JOB_COMPLETED_FAIL"