export const ALL_JOBS_REQUEST = "ALL_JOBS_REQUEST"
export const ALL_JOBS_SUCCESS = "ALL_JOBS_SUCCESS"
export const ALL_JOBS_FAIL = "ALL_JOBS_FAIL"

export const JOB_APPLY_REQUEST = "JOB_APPLY_REQUEST"
export const JOB_APPLY_SUCCESS = "JOB_APPLY_SUCCESS"
export const JOB_APPLY_FAIL = "JOB_APPLY_FAIL"